### ISSUE TITLE
Icon Request Loader not detecting installed apps with icon

### ISSUE THREAD

**Issue by randomvector** [danimahardhika/candybar-library#82]
When updating the Candybar Library core from 3.2.2 to 3.3.0 the icon request loader on the home screen does not detect the apps that have associated icons. Works as it should on version 3.2.2. I have cleaned the project before building and changed no other code between updates.

**Comment by danimahardhika** [comment]
Someone also report it in G+ community [here](https://plus.google.com/u/1/114688688163385846524/posts/2vPB8kzrHup). Since there's not enough information, I still not able to confirm if this is a bug.

Try to use the SNAPSHOT. Open `build.gradle` and change `compile 'com.github.danimahardhika.candybar-library:core:3.3.0'` to ` compile 'com.github.danimahardhika.candybar-library:core:-SNAPSHOT'`.

And tell me the error message appear.

**Comment by randomvector** [comment]
Hi I compiled the SNAPSHOT as requested. When launching activity it pops up with "Error: Unable to read appfilter.xml" toast

**Comment by danimahardhika** [comment]
@randomvector Could you please send your appfilter.xml to me?

**Comment by randomvector** [comment]
Can I send it privately?

**Comment by danimahardhika** [comment]
Yes you can send it via hangouts or directly to my email danimahardhika112[at]gmail[dot]com

**Comment by randomvector** [comment]
Thanks. I've emailed it to you

**Comment by danimahardhika** [comment]
Turns out this is happened because there's a mistake in your appfilter.xml. Check line 65, 
`<item component="ComponentInfo{com.android.dialer/com.android.dialer.DialtactsActivity}" prefix="phone" />`, it should be
 `<item component="ComponentInfo{com.android.dialer/com.android.dialer.DialtactsActivity}" drawable="phone" />`

**Comment by randomvector** [comment]
I changed the code but the icon loader still doesn't load apps with icons on 3.3.0

**Comment by danimahardhika** [comment]
@randomvector Check line 65, 423, 442, and 810 too.

**Comment by randomvector** [comment]
HI,

Thanks that fixed it! drawgooble=lol

Really appreciate your help 👍
